In [37]:
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from skimage import io,transform
import tensorflow as tf
from keras.layers import Input, Dense, Activation
from keras.models import Model
from keras.layers import Conv2D, Flatten, MaxPool2D
from keras.optimizers import SGD, RMSprop, adam
from keras.utils import to_categorical
from keras.callbacks import TensorBoard
from PIL import Image
from keras.preprocessing.image import ImageDataGenerator
from skimage.transform import hough_circle, hough_circle_peaks
from skimage.feature import canny
from skimage.draw import circle_perimeter
from skimage.util import img_as_ubyte
from skimage import color
from keras.preprocessing import image
from keras.utils import generic_utils

In [38]:
w = 224
h = 224
c = 3
path = '/Users/Philixsmacbook/Desktop/Images'

imgs = []
label = []
count = 0
for train_class in os.listdir(path):
    for pic in os.listdir(path+'/'+train_class):
        img = io.imread(path+'/'+train_class+'/'+pic)
        img = transform.resize(img,(w,h,c))
        imgs.append(img)
        label.append(train_class)
        temp = np.array([imgs,label])
        temp = temp.transpose()
        np.random.shuffle(temp)
        image_list = list(temp[:,0])
        label_list = list(temp[:,1])
        count += 1
    

/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/skimage/transform/_warps.py:84: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "


In [39]:
nb_images = int(0.8*count)
x_train = np.array(image_list[:nb_images])
y_train = np.array(label_list[:nb_images])

nb_test = int(0.2*count)
x_test = np.array(image_list[:nb_test])
y_test = np.array(label_list[:nb_test])
print (x_test, y_train)


[[[[0.28311691 0.24117647 0.87543913]
   [0.28366736 0.23728558 0.87386643]
   [0.28806168 0.23594321 0.8730951 ]
   ...
   [0.28598476 0.22740151 0.87090489]
   [0.28968686 0.22844896 0.87140816]
   [0.29030061 0.23234419 0.87265698]]

  [[0.28333481 0.23333333 0.87287435]
   [0.28349236 0.23333333 0.8727168 ]
   [0.28016457 0.22438765 0.86979471]
   ...
   [0.27813926 0.22156863 0.87058824]
   [0.28786173 0.22012418 0.87042196]
   [0.29171908 0.22482493 0.87009364]]

  [[0.28300654 0.22741292 0.87122914]
   [0.28296569 0.22486432 0.87039128]
   [0.27863487 0.21723338 0.86893966]
   ...
   [0.28153308 0.22322417 0.86965966]
   [0.28883637 0.22158613 0.86993464]
   [0.28964702 0.22221639 0.86939243]]

  ...

  [[0.37676948 0.25091759 0.86980917]
   [0.37553118 0.25489778 0.87124322]
   [0.36779365 0.24775051 0.86946233]
   ...
   [0.4441874  0.28109017 0.87398205]
   [0.43922126 0.28232629 0.87303902]
   [0.44910962 0.28400012 0.87461434]]

  [[0.37276783 0.25456491 0.87113826]
   [0.3

In [40]:
from keras.layers import Convolution2D, MaxPooling2D, concatenate, Dropout
from keras.layers import GlobalAveragePooling2D

In [41]:
sq1x1 = "squeeze1x1"
exp1x1 = "expand1x1"
exp3x3 = "expand3x3"
relu = "relu_"

def fire_module(x, fire_id, squeeze=16, expand=64):
   s_id = 'fire' + str(fire_id) + '/'
   x = Convolution2D(squeeze, (1, 1), padding='valid', name=s_id + sq1x1)(x)
   x = Activation('relu', name=s_id + relu + sq1x1)(x)

   left = Convolution2D(expand, (1, 1), padding='valid', name=s_id + exp1x1)(x)
   left = Activation('relu', name=s_id + relu + exp1x1)(left)

   right = Convolution2D(expand, (3, 3), padding='same', name=s_id + exp3x3)(x)
   right = Activation('relu', name=s_id + relu + exp3x3)(right)

   x = concatenate([left, right], axis=3, name=s_id + 'concat')
   return x

def SqueezeNet():
    inputs = Input(shape=(224, 224, 3))
    x = Convolution2D(64, (3, 3), strides=(2, 2), padding='valid', name='conv1')(inputs)
    x = Activation('relu', name='relu_conv1')(x)
    x = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), name='pool1')(x)
    
    x = fire_module(x, fire_id=2, squeeze=16, expand=64)
    x = fire_module(x, fire_id=3, squeeze=16, expand=64)
    x = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), name='pool3')(x)
    
    x = fire_module(x, fire_id=4, squeeze=32, expand=128)
    x = fire_module(x, fire_id=5, squeeze=32, expand=128)
    x = MaxPooling2D(pool_size=(3, 3), strides=(2, 2), name='pool5')(x)
    
    x = fire_module(x, fire_id=6, squeeze=48, expand=192)
    x = fire_module(x, fire_id=7, squeeze=48, expand=192)
    x = fire_module(x, fire_id=8, squeeze=64, expand=256)
    x = fire_module(x, fire_id=9, squeeze=64, expand=256)
    x = Dropout(0.5, name='drop9')(x)
    
    x = Convolution2D(4, (1, 1), padding='valid', name='conv10')(x)
    x = Activation('relu', name='relu_conv10')(x)
    x = GlobalAveragePooling2D()(x)
    out = Activation('softmax', name='loss')(x)
    
    model = Model(inputs, out, name='squeezenet')
    return model

model = SqueezeNet()

In [42]:
model.compile(optimizer='adam',loss='categorical_crossentropy', metrics=['accuracy'])
#
y_train_prob = to_categorical(y_train)
#print(y_train_small_prob)
y_test_prob = to_categorical(y_test)

In [43]:
epochs = 15
batch_size = 32
log_dir = 'logs/'
tb_callback = TensorBoard(log_dir, histogram_freq=1, write_graph=True, write_images=False, embeddings_freq=0, embeddings_layer_names=None, embeddings_metadata=None)
img_generator = ImageDataGenerator(rotation_range = 90,
                              width_shift_range = 0.2,
                              height_shift_range = 0.2,
                              zoom_range = 0.3)

img_generator.fit(x_train)

model.fit_generator(img_generator.flow(x_train, y_train_prob, batch_size=batch_size),
                    steps_per_epoch=len(x_train), epochs=epochs, validation_data = (x_test, y_test_prob), callbacks=[tb_callback])

Epoch 1/15
336/336 [==============================] - 702s 2s/step - loss: 1.3233 - acc: 0.3951 - val_loss: 1.3007 - val_acc: 0.4405


InvalidArgumentError: You must feed a value for placeholder tensor 'input_4' with dtype float and shape [?,224,224,3]
	 [[Node: input_4 = Placeholder[dtype=DT_FLOAT, shape=[?,224,224,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'input_4', defined at:
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-8c45f7de34c0>", line 48, in <module>
    model = SqueezeNet()
  File "<ipython-input-27-8c45f7de34c0>", line 21, in SqueezeNet
    inputs = Input(shape=(224, 224, 3))
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/keras/engine/input_layer.py", line 176, in Input
    input_tensor=tensor)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/keras/engine/input_layer.py", line 85, in __init__
    name=self.name)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 514, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1808, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4848, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/Philixsmacbook/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_4' with dtype float and shape [?,224,224,3]
	 [[Node: input_4 = Placeholder[dtype=DT_FLOAT, shape=[?,224,224,3], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
